server:
  port: 80
spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: 192.168.1.130
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #不写这个配置，在docker下的consul里面健康检查会失败
        prefer-ip-address: true