server:
  port: 7001
eureka:
  instance:
    #单机的时候这样配置
#    hostname: localhost
    #集群的时候可以这样配置
    hostname: eureka7001.com
  client:
    #\u4E0D\u9700\u8981\u81EA\u5DF1\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #单机的时候这样配置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/